### ISSUE TITLE
Program crushes after calling m_camera_model.project3dToPixel(pt_cv);

### ISSUE THREAD

**Issue by allenthreee** [sungwook87/mlcpp#1]
as the title said, the program crushes after calling 
uv = [m_camera_model.project3dToPixel(pt_cv);](https://github.com/sungwook87/mlcpp/blob/3f2a68cc1d446388e761b3d2aac350911284c90f/include/mlcpp_main.h#L559)

**Comment by engcang** [comment]
@allenthreee Hi.
Did you set the cam intrinsic parameter in .launch file properly?
https://github.com/sungwook87/mlcpp/blob/3f2a68cc1d446388e761b3d2aac350911284c90f/launch/main.launch#L13

**Comment by allenthreee** [comment]
Thank you for your reply, I changed a computer and things worked out fine.
Maybe it's because of the OpenCV version

**Comment by engcang** [comment]
@allenthreee Sounds great!
Closing the issue.
